daviszhen/matrixone

cmd/db-server/main.go
pkg/vm/driver/cube_driver.go
pkg/vm/driver/kv/executor.go
pkg/vm/driver/kv/malloc.go
pkg/vm/engine/tpe/engine/engine.go
pkg/vm/engine/tpe/engine/types.go
pkg/vm/engine/tpe/orderedcodec/decoder.go
pkg/vm/engine/tpe/tuplecodec/decoder.go
pkg/vm/engine/tpe/tuplecodec/indexhandler.go
pkg/vm/engine/tpe/tuplecodec/serialize.go

issue #
Not Available
Not Available
Not Available

update cubekv for new cube client

---

pkg/vm/engine/tpe/engine/reader_test.go
pkg/vm/engine/tpe/engine/relation_test.go
pkg/vm/engine/tpe/tuplecodec/computationhandler.go

issue #
Not Available
Not Available
Not Available

fix ut failures

---

pkg/sql/compile2/compile.go
pkg/sql/compile2/scope.go
pkg/sql/plan2/build_ddl.go

issue #
Not Available
Not Available
Not Available

Surpport to run ddl successfully

---

pkg/frontend/mysql_cmd_executor.go
pkg/frontend/session.go
pkg/frontend/variables.go

issue #
Not Available
Not Available
Not Available

update variables for jdbc compatibility

---

pkg/frontend/mysql_cmd_executor.go
pkg/frontend/mysql_cmd_executor_test.go
pkg/frontend/session.go
pkg/frontend/types.go
pkg/frontend/util.go
pkg/frontend/util_test.go
pkg/frontend/variables.go

issue #
Not Available
Not Available
Not Available

adapt frontend for jdbc compatibility

---

go.mod
go.sum
pkg/vm/engine/disttae/db.go
pkg/vm/engine/disttae/engine.go

disttae: fix potential deadlock

---

pkg/backup/backpu_test.go
pkg/backup/tae.go
pkg/vm/engine/tae/db/testutil/engine.go
pkg/vm/engine/tae/logtail/handle.go
pkg/vm/engine/tae/logtail/utils.go
pkg/vm/engine/tae/rpc/handle.go

0821 backup

---

pkg/backup/tae.go
pkg/vm/engine/tae/logtail/handle.go

Fix the bug of copying duplicate files

---

pkg/backup/backpu_test.go
pkg/backup/tae.go
pkg/vm/engine/tae/logtail/handle.go
pkg/vm/engine/tae/rpc/handle.go

Add checkpoint version

---

pkg/backup/backup_test.go
pkg/backup/tae.go
pkg/vm/engine/tae/logtail/handle.go
pkg/vm/engine/tae/testutils/config/options.go

0823 fix backup

---

pkg/backup/tae.go
pkg/vm/engine/tae/db/testutil/engine.go

0823 fix sca

---

.github/workflows/merge-trigger.yaml
pkg/vm/engine/disttae/db.go
pkg/vm/engine/disttae/engine.go
pkg/vm/engine/disttae/logtailPullModel.go
pkg/vm/engine/disttae/tools.go
pkg/vm/engine/disttae/txn.go
pkg/vm/engine/disttae/txn_table.go
pkg/vm/engine/disttae/txn_table_test.go
pkg/vm/engine/disttae/types.go

Pick fix 11437

---

.github/workflows/merge-trigger.yaml
pkg/vm/engine/disttae/engine.go
pkg/vm/engine/disttae/partition_reader.go
pkg/vm/engine/disttae/txn.go
pkg/vm/engine/disttae/txn_table.go
pkg/vm/engine/disttae/types.go

Fix 11437 11443 new

---

pkg/frontend/cdc.go
pkg/frontend/self_handle.go
pkg/sql/plan/build.go
pkg/sql/plan/build_show.go
pkg/taskservice/task_service.go
pkg/taskservice/types.go

issue # https://github.com/matrixorigin/MO-Cloud/issues/3866
add create show drop

Add tables parse

---

pkg/cdc/decoder.go
pkg/cdc/partitioner.go
pkg/cdc/sinker.go
pkg/cdc/util.go
pkg/frontend/cdc.go
pkg/frontend/cdc_test.go
pkg/vm/engine/disttae/cdc.go

support pause and resume

---

pkg/cdc/partitioner.go
pkg/cdc/sinker.go
pkg/cdc/watermarkupdater.go
pkg/frontend/cdc.go

subscribe table and add exe pipeline by table

---

pkg/frontend/authenticate.go
pkg/frontend/cdc.go
pkg/frontend/cdc_test.go
pkg/taskservice/mysql_task_storage.go

add privilege check

---

pkg/cdc/decoder.go
pkg/cdc/partitioner.go
pkg/cdc/sinker.go
pkg/cdc/types.go
pkg/cdc/util.go
pkg/cdc/watermarkupdater.go
pkg/frontend/authenticate.go
pkg/frontend/cdc.go
pkg/frontend/predefined.go

add mo_cdc_watermark table

---

pkg/cdc/decoder.go
pkg/cdc/types.go
pkg/cdc/util.go
pkg/frontend/cdc.go

add memory allocator

---

pkg/vm/engine/disttae/change_handle.go
pkg/vm/engine/disttae/logtailreplay/change_handle.go

rm EOF error

---

pkg/vm/engine/disttae/change_handle.go
pkg/vm/engine/test/change_handle_test.go

fix snapshot changes handle

---

pkg/cdc/decoder.go
pkg/cdc/reader.go
pkg/cdc/sinker.go
pkg/cdc/types.go
pkg/cdc/util.go
pkg/cdc/watermarkupdater.go
pkg/frontend/cdc.go
pkg/frontend/cdc_test.go

new sinker

---

pkg/frontend/cdc.go

fix drop panic

---

pkg/common/moerr/error.go
pkg/common/moerr/error_no_ctx.go
pkg/vm/engine/disttae/change_handle.go
pkg/vm/engine/disttae/logtailreplay/change_handle.go

add error stale read

---

pkg/cdc/reader.go
pkg/cdc/sinker.go
pkg/cdc/types.go
pkg/cdc/util.go
pkg/cdc/watermarkupdater.go
pkg/frontend/cdc.go
pkg/frontend/util.go
pkg/taskservice/mysql_task_storage.go

add retry and error handle && remove interChs && fix reader

---

pkg/cdc/reader.go
pkg/cdc/types.go
pkg/cdc/util.go
pkg/frontend/cdc.go
pkg/frontend/predefined.go
pkg/frontend/self_handle.go
pkg/frontend/types.go
pkg/sql/parsers/tree/stmt.go
pkg/sql/plan/build.go
pkg/sql/plan/build_show.go

support no-full option && optimize show task

---

pkg/cdc/sinker.go
pkg/cdc/types.go
pkg/cdc/util.go
pkg/frontend/cdc.go

test all date types
